/*
 * generated by Xtext 2.17.0
 */
package org.xtext.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.Dsl_rimayRuntimeModule
import org.xtext.Dsl_rimayStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class Dsl_rimayIdeSetup extends Dsl_rimayStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new Dsl_rimayRuntimeModule, new Dsl_rimayIdeModule))
	}
	
}
