/*
 * generated by Xtext 2.17.0
 */
package org.xtext


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class Dsl_rimayRuntimeModule extends AbstractDsl_rimayRuntimeModule {
}
