/*
 * generated by Xtext 2.17.0
 */
package org.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class Dsl_rimayStandaloneSetup extends Dsl_rimayStandaloneSetupGenerated {

	def static void doSetup() {
		new Dsl_rimayStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
